In [2]:
import pandas as pd 
from scipy import stats

In [3]:
pf=pd.DataFrame({
    "transaction_ammount": [100,150,250,300,9999]
})

In [5]:
pf

   transaction_ammount
0                  100
1                  150
2                  250
3                  300
4                 9999

In [7]:
pf['Z_score']=stats.zscore(pf['transaction_ammount'])

In [8]:
pf

   transaction_ammount   Z_score
0                  100 -0.525427
1                  150 -0.512673
2                  250 -0.487164
3                  300 -0.474410
4                 9999  1.999675