In [2]:
!pip install polars
!pip install pandas

Requirement already satisfied: polars in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.42.1)
Requirement already satisfied: polars-runtime-32==1.42.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from polars) (1.42.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [3]:
import pandas as pd
import polars as pl

In [4]:
data_list_pd=[[1,"kawsar"],[2,"nasim"]]

In [5]:
pd_representation=pd.DataFrame(data_list_pd,columns=["ID","Name"]) # panda represent with row and colum to name column use argument columns
pd_representation

   ID    Name
0   1  kawsar
1   2   nasim

In [6]:
pl_representation = pl.DataFrame(data_list_pd, schema=["ID", "Name"],orient="row") # polars representation schema work like column and need to set orient
pl_representation

shape: (2, 2)
┌─────┬────────┐
│ ID  ┆ Name   │
│ --- ┆ ---    │
│ i64 ┆ str    │
╞═════╪════════╡
│ 1   ┆ kawsar │
│ 2   ┆ nasim  │
└─────┴────────┘

In [8]:
pd_csv_read=pd.read_csv("sales_data.csv") # pandas csv file read
pd_csv_read

  Month  Product_ID  Sales  Revenue
0   Jan         101    192     9817
1   Jan         102    195     8347
2   Jan         102    194     1544
3   Feb         101     34     1234
4   Feb         102    143     5133
5   Mar         103    252     1235
6   Mar         101    124     1325
7   Mar         102    157     1235
8   Apr         103    123     1235

In [10]:
pl_csv_read=pl.read_csv("sales_data.csv")
pl_csv_read

shape: (9, 4)
┌───────┬────────────┬───────┬─────────┐
│ Month ┆ Product_ID ┆ Sales ┆ Revenue │
│ ---   ┆ ---        ┆ ---   ┆ ---     │
│ str   ┆ i64        ┆ i64   ┆ i64     │
╞═══════╪════════════╪═══════╪═════════╡
│ Jan   ┆ 101        ┆ 192   ┆ 9817    │
│ Jan   ┆ 102        ┆ 195   ┆ 8347    │
│ Jan   ┆ 102        ┆ 194   ┆ 1544    │
│ Feb   ┆ 101        ┆ 34    ┆ 1234    │
│ Feb   ┆ 102        ┆ 143   ┆ 5133    │
│ Mar   ┆ 103        ┆ 252   ┆ 1235    │
│ Mar   ┆ 101        ┆ 124   ┆ 1325    │
│ Mar   ┆ 102        ┆ 157   ┆ 1235    │
│ Apr   ┆ 103        ┆ 123   ┆ 1235    │
└───────┴────────────┴───────┴─────────┘

In [11]:
pl_csv_read.head(3)

shape: (3, 4)
┌───────┬────────────┬───────┬─────────┐
│ Month ┆ Product_ID ┆ Sales ┆ Revenue │
│ ---   ┆ ---        ┆ ---   ┆ ---     │
│ str   ┆ i64        ┆ i64   ┆ i64     │
╞═══════╪════════════╪═══════╪═════════╡
│ Jan   ┆ 101        ┆ 192   ┆ 9817    │
│ Jan   ┆ 102        ┆ 195   ┆ 8347    │
│ Jan   ┆ 102        ┆ 194   ┆ 1544    │
└───────┴────────────┴───────┴─────────┘

In [12]:
pd_csv_read.head(3)

  Month  Product_ID  Sales  Revenue
0   Jan         101    192     9817
1   Jan         102    195     8347
2   Jan         102    194     1544

In [13]:
pl_csv_read.tail(3)

shape: (3, 4)
┌───────┬────────────┬───────┬─────────┐
│ Month ┆ Product_ID ┆ Sales ┆ Revenue │
│ ---   ┆ ---        ┆ ---   ┆ ---     │
│ str   ┆ i64        ┆ i64   ┆ i64     │
╞═══════╪════════════╪═══════╪═════════╡
│ Mar   ┆ 101        ┆ 124   ┆ 1325    │
│ Mar   ┆ 102        ┆ 157   ┆ 1235    │
│ Apr   ┆ 103        ┆ 123   ┆ 1235    │
└───────┴────────────┴───────┴─────────┘

In [14]:
pd_csv_read.tail(3)

  Month  Product_ID  Sales  Revenue
6   Mar         101    124     1325
7   Mar         102    157     1235
8   Apr         103    123     1235

In [15]:
pd_csv_read.describe()

       Product_ID       Sales      Revenue
count    9.000000    9.000000     9.000000
mean   101.888889  157.111111  3456.111111
std      0.781736   61.879812  3448.355457
min    101.000000   34.000000  1234.000000
25%    101.000000  124.000000  1235.000000
50%    102.000000  157.000000  1325.000000
75%    102.000000  194.000000  5133.000000
max    103.000000  252.000000  9817.000000

In [17]:
pd_csv_read.info(verbose=False)

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Columns: 4 entries, Month to Revenue
dtypes: int64(3), str(1)
memory usage: 420.0 bytes

In [ ]:
pd_csv_read.loc[3]   #print 3rd row

Month          Feb
Product_ID     101
Sales           34
Revenue       1234
Name: 3, dtype: object

In [20]:
pd_csv_read.iloc[3]

Month          Feb
Product_ID     101
Sales           34
Revenue       1234
Name: 3, dtype: object

In [21]:
pl_csv_read.describe()

shape: (9, 5)
┌────────────┬───────┬────────────┬────────────┬─────────────┐
│ statistic  ┆ Month ┆ Product_ID ┆ Sales      ┆ Revenue     │
│ ---        ┆ ---   ┆ ---        ┆ ---        ┆ ---         │
│ str        ┆ str   ┆ f64        ┆ f64        ┆ f64         │
╞════════════╪═══════╪════════════╪════════════╪═════════════╡
│ count      ┆ 9     ┆ 9.0        ┆ 9.0        ┆ 9.0         │
│ null_count ┆ 0     ┆ 0.0        ┆ 0.0        ┆ 0.0         │
│ mean       ┆ null  ┆ 101.888889 ┆ 157.111111 ┆ 3456.111111 │
│ std        ┆ null  ┆ 0.781736   ┆ 61.879812  ┆ 3448.355457 │
│ min        ┆ Apr   ┆ 101.0      ┆ 34.0       ┆ 1234.0      │
│ 25%        ┆ null  ┆ 101.0      ┆ 124.0      ┆ 1235.0      │
│ 50%        ┆ null  ┆ 102.0      ┆ 157.0      ┆ 1325.0      │
│ 75%        ┆ null  ┆ 102.0      ┆ 194.0      ┆ 5133.0      │
│ max        ┆ Mar   ┆ 103.0      ┆ 252.0      ┆ 9817.0      │
└────────────┴───────┴────────────┴────────────┴─────────────┘

In [23]:
pd_csv_read.shape

(9, 4)

In [24]:
pl_csv_read.schema

Schema([('Month', String),
        ('Product_ID', Int64),
        ('Sales', Int64),
        ('Revenue', Int64)])