In [44]:
import pandas as pd
import polars as pl

In [45]:
simple_list=[1,2,3,4,5]

In [46]:
s_pandas=pd.Series(simple_list) #just same as pandas read
s_pandas

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [47]:
s_polars=pl.Series("example List",simple_list)
s_polars

shape: (5,)
Series: 'example List' [i64]
[
	1
	2
	3
	4
	5
]

# Data Attribute

In [48]:
s_pandas.dtype

dtype('int64')

In [49]:
s_pandas.shape

(5,)

In [50]:
s_pandas.name

In [51]:
s_polars.dtype

Int64

In [52]:
s_polars.name

'example List'

In [53]:
s_pandas.sum()

np.int64(15)

In [54]:
s_pandas.unique()

array([1, 2, 3, 4, 5])

Data Frame Operation

In [55]:
sale_data_pd=pd.read_csv("sales_data.csv")

In [56]:
sale_data_pd.set_index("Month")

       Product_ID  Sales  Revenue
Month
Jan           101    192     9817
Jan           102    195     8347
Jan           102    194     1544
Feb           101     34     1234
Feb           102    143     5133
Mar           103    252     1235
Mar           101    124     1325
Mar           102    157     1235
Apr           103    123     1235

In [ ]:
sale_data_pd.set_index("Month",inplace=True) # help to set index as month and inplace use to change the index order parmanent without variable

In [59]:
sale_data_pd

       Product_ID  Sales  Revenue
Month
Jan           101    192     9817
Jan           102    195     8347
Jan           102    194     1544
Feb           101     34     1234
Feb           102    143     5133
Mar           103    252     1235
Mar           101    124     1325
Mar           102    157     1235
Apr           103    123     1235

In [ ]:
sale_data_pd.reset_index() # reset the index order

  Month  Product_ID  Sales  Revenue
0   Jan         101    192     9817
1   Jan         102    195     8347
2   Jan         102    194     1544
3   Feb         101     34     1234
4   Feb         102    143     5133
5   Mar         103    252     1235
6   Mar         101    124     1325
7   Mar         102    157     1235
8   Apr         103    123     1235

In [ ]:
sale_data_pd.select("Sales")