In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'

# Load the dataset
data = pd.read_csv(url, header=None, na_values='?')

In [3]:
data

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [4]:
data.isnull().sum()

0       1
1       0
2       0
3      60
4      24
5      58
6      56
7      69
8      47
9      32
10     55
11     44
12     56
13    104
14    106
15    247
16    102
17    118
18     29
19     33
20    165
21    198
22      1
23      0
24      0
25      0
26      0
27      0
dtype: int64

In [5]:
data1=data.interpolate()

In [6]:
data1

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.50,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.20,88.0,20.0,2.0,2.0,4.0,1.0,...,50.0,85.0,2.000000,2.000000,3.0,2,2208,0,0,2
2,2.0,1,530334,38.30,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,2.500000,3.650000,1.0,2,0,0,0,1
3,1.0,9,5290409,39.10,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.000000,5.300000,2.0,1,2208,0,0,1
4,2.0,1,530255,37.30,104.0,35.0,3.0,1.0,6.0,2.0,...,74.0,7.4,2.666667,4.783333,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,37.85,120.0,70.0,4.0,1.5,4.0,2.0,...,55.0,65.0,2.750000,2.866667,3.0,2,3205,0,0,2
296,2.0,1,527702,37.20,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,35.9,3.000000,3.300000,3.0,1,2208,0,0,1
297,1.0,1,529386,37.50,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,3.000000,3.350000,2.0,1,3205,0,0,2
298,1.0,1,530612,36.50,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.000000,3.400000,1.0,1,2208,0,0,1
299,1.0,1,534618,37.20,40.0,20.0,3.0,3.0,3.0,1.0,...,36.0,62.0,1.000000,1.000000,3.0,2,6112,0,0,2

In [ ]:
data1.isnull().sum()  #still have some null values because it can't work with string data and if before or after value is missing then it not work

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     0
10    0
11    0
12    0
13    3
14    3
15    3
16    0
17    0
18    0
19    0
20    1
21    1
22    0
23    0
24    0
25    0
26    0
27    0
dtype: int64

In [ ]:
data2=data.fillna(data.mean())   #more efficient to use

In [10]:
data2

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.500000,66.0,28.0,3.000000,3.000000,2.853755,2.00000,...,45.0,8.400000,2.037037,3.019608,2.0,2,11300,0,0,2
1,1.0,1,534817,39.200000,88.0,20.0,2.348361,2.017316,4.000000,1.00000,...,50.0,85.000000,2.000000,2.000000,3.0,2,2208,0,0,2
2,2.0,1,530334,38.300000,40.0,24.0,1.000000,1.000000,3.000000,1.00000,...,33.0,6.700000,2.037037,3.019608,1.0,2,0,0,0,1
3,1.0,9,5290409,39.100000,164.0,84.0,4.000000,1.000000,6.000000,2.00000,...,48.0,7.200000,3.000000,5.300000,2.0,1,2208,0,0,1
4,2.0,1,530255,37.300000,104.0,35.0,2.348361,2.017316,6.000000,2.00000,...,74.0,7.400000,2.037037,3.019608,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,38.167917,120.0,70.0,4.000000,2.017316,4.000000,2.00000,...,55.0,65.000000,2.037037,3.019608,3.0,2,3205,0,0,2
296,2.0,1,527702,37.200000,72.0,24.0,3.000000,2.000000,4.000000,2.00000,...,44.0,24.456929,3.000000,3.300000,3.0,1,2208,0,0,1
297,1.0,1,529386,37.500000,72.0,30.0,4.000000,3.000000,4.000000,1.00000,...,60.0,6.800000,2.037037,3.019608,2.0,1,3205,0,0,2
298,1.0,1,530612,36.500000,100.0,24.0,3.000000,3.000000,3.000000,1.00000,...,50.0,6.000000,3.000000,3.400000,1.0,1,2208,0,0,1
299,1.0,1,534618,37.200000,40.0,20.0,2.348361,2.017316,2.853755,1.30597,...,36.0,62.000000,1.000000,1.000000,3.0,2,6112,0,0,2

In [ ]:
data2.isnull().sum() #it show no data has null value

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
dtype: int64

In [12]:
data2["adjusted_data"]=data2[3].map(lambda x:x*1.1)

In [13]:
data2["Mean_row"]=data.apply(lambda row:row.mean(),axis=1) #axis=1 mean row 0 mean column,

In [14]:
data2

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,adjusted_data,Mean_row
0,2.0,1,530101,38.500000,66.0,28.0,3.000000,3.000000,2.853755,2.00000,...,2.037037,3.019608,2.0,2,11300,0,0,2,42.350000,24619.313636
1,1.0,1,534817,39.200000,88.0,20.0,2.348361,2.017316,4.000000,1.00000,...,2.000000,2.000000,3.0,2,2208,0,0,2,43.120000,23362.617391
2,2.0,1,530334,38.300000,40.0,24.0,1.000000,1.000000,3.000000,1.00000,...,2.037037,3.019608,1.0,2,0,0,0,1,42.130000,23065.130435
3,1.0,9,5290409,39.100000,164.0,84.0,4.000000,1.000000,6.000000,2.00000,...,3.000000,5.300000,2.0,1,2208,0,0,1,43.010000,196037.614815
4,2.0,1,530255,37.300000,104.0,35.0,2.348361,2.017316,6.000000,2.00000,...,2.037037,3.019608,2.0,2,4300,0,0,2,41.030000,33426.856250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,38.167917,120.0,70.0,4.000000,2.017316,4.000000,2.00000,...,2.037037,3.019608,3.0,2,3205,0,0,2,41.984708,28285.842105
296,2.0,1,527702,37.200000,72.0,24.0,3.000000,2.000000,4.000000,2.00000,...,3.000000,3.300000,3.0,1,2208,0,0,1,40.920000,20389.788462
297,1.0,1,529386,37.500000,72.0,30.0,4.000000,3.000000,4.000000,1.00000,...,2.037037,3.019608,2.0,1,3205,0,0,2,41.250000,21313.532000
298,1.0,1,530612,36.500000,100.0,24.0,3.000000,3.000000,3.000000,1.00000,...,3.000000,3.400000,1.0,1,2208,0,0,1,40.150000,19743.662963
299,1.0,1,534618,37.200000,40.0,20.0,2.348361,2.017316,2.853755,1.30597,...,1.000000,1.000000,3.0,2,6112,0,0,2,40.920000,30052.288889