In [1]:
import pandas as pd

In [2]:
data1=pd.read_csv("data1.csv")
data2=pd.read_csv("data2.csv")

In [4]:
data1

   product_id   Product  Price
0         101    Laptop    800
1         102     Mouse     20
2         103  Keyboard     50

In [5]:
data2

   product_id  Sales
0         101     15
1         102     30
2         104     10

In [ ]:
pd.merge(data1,data2,on="product_id",how="right")  #marge two table based on product_id and show all that is on right (data2)

   product_id Product  Price  Sales
0         101  Laptop  800.0     15
1         102   Mouse   20.0     30
2         104     NaN    NaN     10