In [1]:
!pip install pandas
!pip install polars

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: polars in .\.venv\Lib\site-packages (1.42.1)
Requirement already satisfied: polars-runtime-32==1.42.1 in .\.venv\Lib\site-packages (from polars) (1.42.1)

In [2]:
import pandas as pd 
import polars as pl

In [3]:
read_csv_pd=pd.read_csv("Monthly Sales.csv")
read_csv_pd_missing=pd.read_csv("Monthly Sales with misssing values.csv")

In [4]:
read_csv_pd.describe()

        product_id        sales
count   240.000000   240.000000
mean   1010.500000   792.983333
std       5.778332   280.185637
min    1001.000000   285.000000
25%    1005.750000   559.750000
50%    1010.500000   772.500000
75%    1015.250000  1020.250000
max    1020.000000  1601.000000

In [5]:
read_csv_pd.info(verbose=False)

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Columns: 3 entries, month to sales
dtypes: int64(2), str(1)
memory usage: 5.8 KB

In [6]:
read_csv_pd.isnull().sum() #without Missing values

month         0
product_id    0
sales         0
dtype: int64

In [7]:
read_csv_pd_missing.isnull().sum() #with missing values

month         24
product_id    24
sales         24
dtype: int64

In [8]:
read_csv_pd_missing.dropna() # my original file in 240x3 but it show only 177 because it remove missing row that is not ideal

        month  product_id   sales
0     January      1001.0   347.0
3     January      1004.0  1122.0
4     January      1005.0   716.0
5     January      1006.0   877.0
6     January      1007.0   614.0
..        ...         ...     ...
234  December      1015.0  1162.0
235  December      1016.0   428.0
236  December      1017.0  1087.0
237  December      1018.0   779.0
238  December      1019.0   682.0

[177 rows x 3 columns]

In [9]:
pd_filled_with_zero=read_csv_pd_missing.fillna(0) #replace missing value with zero

In [10]:
pd_filled_with_zero

        month  product_id   sales
0     January      1001.0   347.0
1           0      1002.0   401.0
2     January      1003.0     0.0
3     January      1004.0  1122.0
4     January      1005.0   716.0
..        ...         ...     ...
235  December      1016.0   428.0
236  December      1017.0  1087.0
237  December      1018.0   779.0
238  December      1019.0   682.0
239  December      1020.0     0.0

[240 rows x 3 columns]

In [11]:
read_csv_pd_missing["product_id"].interpolate() #there is some problem with interpolate it work with only integer value not string that's why we can't interpolate all the column

0      1001.0
1      1002.0
2      1003.0
3      1004.0
4      1005.0
        ...
235    1016.0
236    1017.0
237    1018.0
238    1019.0
239    1020.0
Name: product_id, Length: 240, dtype: float64

In [12]:
#to do interpolate that looks okey will be 
read_csv_pd_missing[["product_id","sales"]]=read_csv_pd_missing[["product_id","sales"]].interpolate()

In [13]:
read_csv_pd_missing   #now no null value

        month  product_id   sales
0     January      1001.0   347.0
1         NaN      1002.0   401.0
2     January      1003.0   761.5
3     January      1004.0  1122.0
4     January      1005.0   716.0
..        ...         ...     ...
235  December      1016.0   428.0
236  December      1017.0  1087.0
237  December      1018.0   779.0
238  December      1019.0   682.0
239  December      1020.0   682.0

[240 rows x 3 columns]

In [14]:
read_csv_pd_missing.isnull().sum()  #sting can't be replaced that's why month has 24

month         24
product_id     0
sales          0
dtype: int64

In [15]:
def double_value(x):
    return x*2

In [ ]:
read_csv_pd["product_id"].map(double_value) #map is use to implement the function

0      2002
1      2004
2      2006
3      2008
4      2010
       ...
235    2032
236    2034
237    2036
238    2038
239    2040
Name: product_id, Length: 240, dtype: int64